export const VALUE_CHANGED = 'VALUE_CHANGED';
export const SOURCE_CHANGED = 'SOURCE_CHANGED';
export const TARGET_CHANGED = 'TARGET_CHANGED';
export const INITIAL_STATE = 'INITIAL_STATE';

// currency api
export const LOAD_CURRENCY_RATES = 'LOAD_CURRENCY_RATES';
export const LOAD_CURRENCY_RATES_SUCCESS = 'LOAD_CURRENCY_RATES_SUCCESS';
export const LOAD_CURRENCY_RATES_FAILED = 'LOAD_CURRENCY_RATES_FAILED';
